version: '3'

networks:
  root_traefik_net:
    external: true

services:
  metabase:
    networks:
      - root_traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metabase.rule=Host(`metabase.test-multi-docker.jacopomarrone.com`)"
      - "traefik.http.services.metabase.loadbalancer.server.port=3000"
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    volumes:
      - ./docker-data/metabase-database:/metabase-database
      - ./docker-data/other-files:/other-files
    environment:
      - MB_DB_FILE=/metabase-database/metabase.db

